server.port=8081

spring.application.name=cdrProducer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producere.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer